# Generated by Django 2.2.4 on 2019-08-15 19:55

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='pics/', validators=[posts.models.validate_picture]),
        ),
    ]
